version: '3'

services:

  browser:
    labels:
      shipyard.route: '/'
    build: 'browser/'
    environment:
      CI: 'true'
      REACT_APP_DEPLOYMENT_MODE: ${REACT_APP_DEPLOYMENT_MODE}
    ports:
      - '3000:3000'

  server:
    build: 'server/'
    ports:
      - '3001:3000'
